spring: 
  application: 
    name: hexagonal
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create  
  h2:
    console:
      settings:
        trace: true 
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest